apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgAqbiQVbDYc/Hf6my8Q/qgL1SSuofteWMcIYRhaAZM6uivgOSkCOg8WnVdypxl08yUSKknsqsCsi4nLp3Yl/vm7DAG/On/Akzpv7b+kq6beQNrURJJajldm7bQb/7KLRj5v74TO6XhuxAp9waMiQiveNZZp2Hjs0fXhtfamk1ibyN+mKlx5B1uTnH+JCAZ+zAabIrULVwKgOEI15dlutlTvByO19IRZxzSuwYgApqQuCsoNkxEwgFlfijBSYVRQxjQyI/Ysai/cKmfqYsbTCzFwSK/+00m+EPIsK+c0ownOrvx+J4RkLHCo51//65A9EAfiLbeESuYpcTGZ/R5oyMyI1QI1Zs632bJYsMjhZ/3yrtn4BwZzMd9Nz569Dsrh0aWFWa1uEcJbHZ6q4u8Sqax2HJ9ZkmVQPlZounXiQoAzSnIaY6InZ0ZfS+Br1AYgC5Jw79AU21VsZyFtjph7MjaS4ipZkNf5LP5LpyTjrC57UkjCSUJo1vGK8N/a0s4l7VhDXyR3PwfOTAfgJPa+c7Dymc4B/KIkZo4albAD+kCNOre2aii4G2oxiWgyPPKpbveCv2/LMxU4bJtJupYv3L7mCj+gYnAdHToW+pfpJBqWQtrPy/zsQ/Ofi4mLo2AXLnD1BVM/AsNGyGT60Ux9/C5JJPlr/4QHZfdX5r1N2r31e9ubfjxUcqbxkZsVZfLRl3iYSBDp8inDLRnqMJJamXeMveC9FUTk8ntDrA0wYrgkTP4lFE+sugKc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

