apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: prod-ref-ss
  spec:
    commonName: appdomain.cloud
    dnsNames:
    - '*.itzroks-6620022xah-hvdd7s-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud'
    isCA: true
    issuerRef:
      kind: Issuer
      name: prod-ref-ss
    secretName: prod-ref-ss-tls-ca-key-pair
    subject:
      countries:
      - UK
      localities:
      - London
      organizationalUnits:
      - Assets and Architecture, Certificate Authority
      organizations:
      - IBM
      provinces:
      - London
kind: List
metadata: {}
